version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: quiz-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-quiz_app}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - quiz-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: quiz-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/${MONGO_DATABASE:-quiz_app}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    networks:
      - quiz-network
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: quiz-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:3001
      - REACT_APP_SOCKET_URL=http://localhost:3001
    depends_on:
      - server
    networks:
      - quiz-network
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  quiz-network:
    driver: bridge